In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
import warnings

warnings.filterwarnings('ignore')

In [4]:
df = pd.read_csv('cardekho_dataset.csv', index_col=[0])

In [5]:
df.head()

,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,Maruti Alto,Maruti,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,Hyundai Grand,Hyundai,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,Hyundai i20,Hyundai,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,Maruti Alto,Maruti,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,Ford Ecosport,Ford,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

### ***Data Cleaning***

In [6]:
df.isnull().sum()

car_name             0
brand                0
model                0
vehicle_age          0
km_driven            0
seller_type          0
fuel_type            0
transmission_type    0
mileage              0
engine               0
max_power            0
seats                0
selling_price        0
dtype: int64

In [9]:
df.drop(columns=['car_name', 'brand'], axis=1, inplace=True)

In [10]:
df.head()

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

In [11]:
df['model'].unique()

array(['Alto', 'Grand', 'i20', 'Ecosport', 'Wagon R', 'i10', 'Venue',
       'Swift', 'Verna', 'Duster', 'Cooper', 'Ciaz', 'C-Class', 'Innova',
       'Baleno', 'Swift Dzire', 'Vento', 'Creta', 'City', 'Bolero',
       'Fortuner', 'KWID', 'Amaze', 'Santro', 'XUV500', 'KUV100', 'Ignis',
       'RediGO', 'Scorpio', 'Marazzo', 'Aspire', 'Figo', 'Vitara',
       'Tiago', 'Polo', 'Seltos', 'Celerio', 'GO', '5', 'CR-V',
       'Endeavour', 'KUV', 'Jazz', '3', 'A4', 'Tigor', 'Ertiga', 'Safari',
       'Thar', 'Hexa', 'Rover', 'Eeco', 'A6', 'E-Class', 'Q7', 'Z4', '6',
       'XF', 'X5', 'Hector', 'Civic', 'D-Max', 'Cayenne', 'X1', 'Rapid',
       'Freestyle', 'Superb', 'Nexon', 'XUV300', 'Dzire VXI', 'S90',
       'WR-V', 'XL6', 'Triber', 'ES', 'Wrangler', 'Camry', 'Elantra',
       'Yaris', 'GL-Class', '7', 'S-Presso', 'Dzire LXI', 'Aura', 'XC',
       'Ghibli', 'Continental', 'CR', 'Kicks', 'S-Class', 'Tucson',
       'Harrier', 'X3', 'Octavia', 'Compass', 'CLS', 'redi-GO', 'Glanza',
       'Macan', 'X4', 'Dzire ZXI', 'XC90', 'F-PACE', 'A8', 'MUX',
       'GTC4Lusso', 'GLS', 'X-Trail', 'XE', 'XC60', 'Panamera', 'Alturas',
       'Altroz', 'NX', 'Carnival', 'C', 'RX', 'Ghost', 'Quattroporte',
       'Gurkha'], dtype=object)

In [13]:
## Getting all types of features
num_features = [feature for feature in df.columns if df[feature].dtypes != 'O']
print('Numerical Features: ', len(num_features))

cat_features = [feature for feature in df.columns if df[feature].dtypes == 'O']
print('Categorical Features: ', len(cat_features))

discrete_features = [feature for feature in num_features if len(df[feature].unique()) <= 25]
print('Discrete Features: ', len(discrete_features))

continuous_features = [feature for feature in num_features if feature not in discrete_features]
print('Continuous Features: ', len(continuous_features))

Numerical Features:  7
Categorical Features:  4
Discrete Features:  2
Continuous Features:  5

In [14]:
## Independent and dependent features
from sklearn.model_selection import train_test_split
X = df.drop(columns=['selling_price'], axis=1)
y = df['selling_price']

In [16]:
X.head()

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats
0,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5
1,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5
2,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5
3,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5
4,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5

## **Feature Encoding and Scaling**

In [18]:
len(df['model'].unique())

120

In [21]:
df['model'].value_counts()

model
i20            906
Swift Dzire    890
Swift          781
Alto           778
City           757
              ...
Ghibli           1
Altroz           1
GTC4Lusso        1
Aura             1
Gurkha           1
Name: count, Length: 120, dtype: int64

In [22]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

X['model'] = le.fit_transform(X['model'])

In [23]:
X.head()

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats
0,7,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5
1,54,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5
2,118,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5
3,7,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5
4,38,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5

In [24]:
## Create Column Transformer with 3 different transformers
num_features = X.select_dtypes(exclude='object').columns
onehot_columns = ['seller_type', 'fuel_type', 'transmission_type']

from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer

numeric_transformer = StandardScaler()
oh_transformer = OneHotEncoder(drop='first')

preprocessor = ColumnTransformer(
    [
        ("OneHotEncoder", oh_transformer, onehot_columns),
        ("StandardScaler", numeric_transformer, num_features)       
    ], remainder='passthrough'
)

In [25]:
X = preprocessor.fit_transform(X)

In [26]:
pd.DataFrame(X)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,-1.519714,0.983562,1.247335,-0.000276,-1.324259,-1.263352,-0.403022
1,1.0,0.0,0.0,0.0,0.0,1.0,1.0,-0.225693,-0.343933,-0.690016,-0.192071,-0.554718,-0.432571,-0.403022
2,1.0,0.0,0.0,0.0,0.0,1.0,1.0,1.536377,1.647309,0.084924,-0.647583,-0.554718,-0.479113,-0.403022
3,1.0,0.0,0.0,0.0,0.0,1.0,1.0,-1.519714,0.983562,-0.360667,0.292211,-0.936610,-0.779312,-0.403022
4,0.0,0.0,1.0,0.0,0.0,0.0,1.0,-0.666211,-0.012060,-0.496281,0.735736,0.022918,-0.046502,-0.403022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15406,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.508844,0.983562,-0.869744,0.026096,-0.767733,-0.757204,-0.403022
15407,0.0,0.0,0.0,0.0,0.0,1.0,1.0,-0.556082,-1.339555,-0.728763,-0.527711,-0.216964,-0.220803,2.073444
15408,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.407551,-0.012060,0.220539,0.344954,0.022918,0.068225,-0.403022
15409,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.426247,-0.343933,72.541850,-0.887326,1.329794,0.917158,2.073444
15410,0.0,0.0,0.0,0.0,0.0,1.0,0.0,-1.024131,-1.339555,-0.825631,-0.407839,0.020999,0.395884,-0.403022

In [27]:
## Splitting the data into train and test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
X_train.shape, X_test.shape

((12328, 14), (3083, 14))

In [28]:
X_train

array([[ 0.        ,  0.        ,  1.        , ...,  1.75390551,
         2.66249771, -0.40302241],
       [ 1.        ,  0.        ,  0.        , ..., -0.55087963,
        -0.38602844, -0.40302241],
       [ 0.        ,  0.        ,  1.        , ...,  0.89033072,
         3.27453006, -0.40302241],
       ...,
       [ 1.        ,  0.        ,  0.        , ..., -0.9366097 ,
        -0.78070786, -0.40302241],
       [ 0.        ,  0.        ,  0.        , ..., -0.55471774,
        -0.43582879, -0.40302241],
       [ 1.        ,  0.        ,  0.        , ..., -0.04616815,
         0.06194201, -0.40302241]])

## **Model Training and model selection**

In [46]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
import numpy as np

In [47]:
## Create a function to fit and predict the model
def evaluate_model(true, predicted):
    mae = mean_absolute_error(true, predicted)
    mse = mean_squared_error(true, predicted)
    r2 = r2_score(true, predicted)  # Rename the function parameter to avoid conflict
    return mae, mse, r2

In [52]:
## Beginning model Training
models = {
    "Linear_Regression": LinearRegression(),
    "Ridge": Ridge(),
    "Lasso": Lasso(),
    "K_Neighbors": KNeighborsRegressor(),
    "Decision_Tree": DecisionTreeRegressor(),
    "Random_Forest_Regressor": RandomForestRegressor()
}

for i in range(len(list(models))):
    model = list(models.values())[i]
    model.fit(X_train, y_train)
    
    ## Make prediction
    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)
    
    ## Evaluate train and test dataset
    model_train_mae, model_train_mse, model_train_r2 = evaluate_model(y_train, y_train_pred)
    model_test_mae, model_test_mse, model_test_r2 = evaluate_model(y_test, y_test_pred)
    model_test_rmse = np.sqrt(model_test_mse)  # Calculate RMSE from MSE
    
    print(f'{list(models.keys())[i]} Model Evaluation')
    
    print('Model Performance on Training Dataset')
    print('Mean Absolute Error: ', model_train_mae)
    print('Mean Squared Error: ', model_train_mse)
    print('R2 Score: ', model_train_r2)
    print('-'*75)
    print('Model Performance on Test Dataset')
    print('Mean Absolute Error: ', model_test_mae)
    print('Mean Squared Error: ', model_test_mse)
    print('Root Mean Squared Error: ', model_test_rmse)
    print('R2 Score: ', model_test_r2)
    print('\n')
    print('='*75)

Linear_Regression Model Evaluation
Model Performance on Training Dataset
Mean Absolute Error:  268101.60708299384
Mean Squared Error:  306756099359.75964
R2 Score:  0.6217719576765959
---------------------------------------------------------------------------
Model Performance on Test Dataset
Mean Absolute Error:  279618.57941584295
Mean Squared Error:  252550062888.5656
Root Mean Squared Error:  502543.5930230985
R2 Score:  0.6645109298852004


===========================================================================
Ridge Model Evaluation
Model Performance on Training Dataset
Mean Absolute Error:  268059.8014688311
Mean Squared Error:  306756818740.9266
R2 Score:  0.6217710706848424
---------------------------------------------------------------------------
Model Performance on Test Dataset
Mean Absolute Error:  279557.2168930274
Mean Squared Error:  252540243247.96863
Root Mean Squared Error:  502533.8229890289
R2 Score:  0.6645239743566809


===========================================================================
Lasso Model Evaluation
Model Performance on Training Dataset
Mean Absolute Error:  268099.22264981153
Mean Squared Error:  306756104248.3742
R2 Score:  0.6217719516489697
---------------------------------------------------------------------------
Model Performance on Test Dataset
Mean Absolute Error:  279614.7461034126
Mean Squared Error:  252549134806.78134
Root Mean Squared Error:  502542.66963789385
R2 Score:  0.6645121627547996


===========================================================================
K_Neighbors Model Evaluation
Model Performance on Training Dataset
Mean Absolute Error:  91425.47047371836
Mean Squared Error:  106193217845.55484
R2 Score:  0.8690645337531115
---------------------------------------------------------------------------
Model Performance on Test Dataset
Mean Absolute Error:  112526.34609146934
Mean Squared Error:  64021344520.150826
Root Mean Squared Error:  253024.39510875393
R2 Score:  0.9149536488136147


===========================================================================
Decision_Tree Model Evaluation
Model Performance on Training Dataset
Mean Absolute Error:  5164.819922128488
Mean Squared Error:  432524990.53644824
R2 Score:  0.9994666998284044
---------------------------------------------------------------------------
Model Performance on Test Dataset
Mean Absolute Error:  125451.36501243379
Mean Squared Error:  97708377535.16145
Root Mean Squared Error:  312583.39292924927
R2 Score:  0.8702035851950634


===========================================================================
Random_Forest_Regressor Model Evaluation
Model Performance on Training Dataset
Mean Absolute Error:  39789.11760376899
Mean Squared Error:  17262193477.082138
R2 Score:  0.9787158408303157
---------------------------------------------------------------------------
Model Performance on Test Dataset
Mean Absolute Error:  101725.74782461564
Mean Squared Error:  52063073396.5935
Root Mean Squared Error:  228173.3406789529
R2 Score:  0.9308390903515688


===========================================================================

### ***HyperParameter Tunning***

In [63]:
## Initialize few paramter for hyperparameter tuning
knn_params = {
    "n_neighbours" : [2, 3, 10, 20, 40, 50]
}
rf_params = {
    "max_depth" : [5, 8, 15, None, 10],
    "max_features" : [5, 7, "auto", 8],
    "min_samples_split" : [2, 8, 15, 20],
    "n_estimators" : [100, 200, 500, 1000]
}

In [64]:
## Models list for hyperparameter tuning
randomcv_models = [
    ("KNN", KNeighborsRegressor(), knn_params),
    ("RF", RandomForestRegressor(), rf_params)
]

In [65]:
from sklearn.model_selection import RandomizedSearchCV

model_param = {}
for name, model, params in randomcv_models:
    random = RandomizedSearchCV(
        estimator=model,
        param_distributions=params,
        n_iter=100,
        cv=3,
        verbose=2,
        n_jobs=-1
    )
    
    random.fit(X_train, y_train)
    model_param[name] = random.best_params_
    
for model_name in model_param:
    print(f'{model_name} Best Parameters: {model_param[model_name]}')

OSError: [Errno 22] Invalid argument